### ISSUE TITLE
Aprimoramento e correção geral

### ISSUE THREAD

**Issue by VFGarciaDev** [lucaoskaique/resgatemais#31]
### Descrição

- Padronização da nomeação de pastas e arquivos
- Padronização da organização de pastas
- Correção na renderização do componente Carrossel
- Aprimoramento de funcionalidades dos componentes
- Filtragem da configuração do Tailwind

### Sugestão de implementação

Problema com componente Carrossel:
![image](https://github.com/user-attachments/assets/a8be3158-81b1-4fa9-a561-2ee8111ffb67)

**Comment by gabriel-chagas-albuquerque** [comment]
@VFGarciaDev Oq foi q deu ruim na renderização do carrossel?
